name: white_card
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  flutter_lints: ^1.0.0
  shared_preferences: ^2.0.7
  google_sign_in: ^5.0.1
  equatable: ^2.0.3
  cached_network_image: ^3.1.0
  http: ^0.13.1
  device_info: ^2.0.0
  path_provider: ^2.0.1
  image_picker: ^0.8.1+3
  flutter_markdown: ^0.6.2
  animations: ^2.0.0
  drop_shadow_image: ^0.9.1
  flutter_svg: ^0.22.0
  flutter_bloc: ^7.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  logger: ^1.1.0
  json_theme: ^3.3.1
  file_picker: ^4.6.0
  encrypt: ^5.0.1
  introduction_screen:
    git:
      url: https://github.com/saquibansari0101/introduction_screen
  email_validator: ^2.0.1
  firebase_storage: ^10.2.17
  share_plus: ^4.0.4
  flutter_downloader: ^1.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway.ttf
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 700